name: contact.paulienoel
services:
  postgresql:
    image: postgres:17-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgresql:/var/lib/postgresql/data

  smtp4dev:
    image: rnwood/smtp4dev:latest
    ports:
      - ${SMTP4DEV_WEB_PORT:-5001}:80
      - ${SMTP_PORT:-1025}:25
    volumes:
      - smtp4dev:/smtp4dev

volumes:
  postgresql:
  smtp4dev:
