import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'quote_requests'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table
        .specificType('id', 'bigint generated by default as identity')
        .primary()
      table.text('full_name').notNullable()
      table.text('email').notNullable()
      table.text('phone').nullable()
      table.text('company_name').nullable()
      table.text('website_url').nullable()
      table.text('project_description').notNullable()
      table.text('desired_timeline').notNullable()
      table.integer('budget_cents').nullable()
      table.jsonb('selections').notNullable()
      table.jsonb('estimate_lines').notNullable()
      table.integer('estimate_low_cents').notNullable()
      table.integer('estimate_high_cents').notNullable()
      table.specificType('currency', 'char(3)').notNullable()
      table.text('notification_status').notNullable().defaultTo('pending')
      table.timestamp('notification_attempted_at', { useTz: true }).nullable()
      table.timestamp('notification_sent_at', { useTz: true }).nullable()
      table.text('notification_error').nullable()
      table
        .timestamp('last_contact_at', { useTz: true })
        .notNullable()
        .defaultTo(this.now())
      table
        .timestamp('purge_after', { useTz: true })
        .notNullable()
        .defaultTo(this.raw("CURRENT_TIMESTAMP + INTERVAL '3 years'"))
      table
        .timestamp('created_at', { useTz: true })
        .notNullable()
        .defaultTo(this.now())
      table
        .timestamp('updated_at', { useTz: true })
        .notNullable()
        .defaultTo(this.now())

      table.check(
        "desired_timeline IN ('flexible', 'normal', 'express')",
        undefined,
        'quote_requests_desired_timeline_check',
      )
      table.check(
        'budget_cents IS NULL OR budget_cents >= 0',
        undefined,
        'quote_requests_budget_check',
      )
      table.check(
        'estimate_low_cents >= 0',
        undefined,
        'quote_requests_estimate_low_check',
      )
      table.check(
        'estimate_high_cents >= estimate_low_cents',
        undefined,
        'quote_requests_estimate_range_check',
      )
      table.check(
        "currency = 'EUR'",
        undefined,
        'quote_requests_currency_check',
      )
      table.check(
        "notification_status IN ('pending', 'sent', 'failed')",
        undefined,
        'quote_requests_notification_status_check',
      )
      table.check(
        "notification_status <> 'sent' OR notification_sent_at IS NOT NULL",
        undefined,
        'quote_requests_sent_notification_check',
      )
      table.check(
        "notification_status <> 'failed' OR notification_attempted_at IS NOT NULL",
        undefined,
        'quote_requests_failed_notification_check',
      )
      table.check(
        "purge_after = last_contact_at + INTERVAL '3 years'",
        undefined,
        'quote_requests_retention_check',
      )

      table.index(['purge_after'], 'quote_requests_purge_after_index')
      table.index(
        ['notification_status'],
        'quote_requests_notification_status_index',
      )
      table.index(['created_at'], 'quote_requests_created_at_index')
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
